package ppp;

import java.io.IOException;


import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class Login
 */
@WebServlet("/Login")
public class Login extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Login() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
		PrintWriter out=response.getWriter();
		String userid=request.getParameter("userid");
		String password=request.getParameter("password");
		HttpSession session=request.getSession();
				boolean flag=false;
				
		int otp=new Random().nextInt(900000)+100000;
		
		
		try
		{
			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
			Statement stmt=con.createStatement();
			ResultSet rs=stmt.executeQuery("select * from voters");
			System.out.println("Hello ");
			while(rs.next())
			{
				System.out.println("Hello 1");
				System.out.println("Hello "+rs.getString(8));
				System.out.println("Hello "+rs.getString(9));
				if(userid.equals(rs.getString(8))&& password.equals(rs.getString(9)))
				{
					System.out.println("Hello 2");
					flag=true;
				if(rs.getString(13)!=null)
					{
						System.out.println("Hello 3");
						session.setAttribute("emailid", userid);
						session.setAttribute("otp", otp);
						flag=true;
						SendOtp.send(userid,otp);
						Double number=rs.getDouble(6);
						String apiKey="s1bapN2kQdCqGvzmRK3xYFi6U4O5MjDyEwur0XcHe7VIAl9SfB2Aj0h7qCm4iIUlvoSVTQ6R1FrYEcyJ";
						System.out.println("Hello 4");
						Otp s = new Otp();
//						s.SendOtp("Hey , OTP generated by Chocolate Cake "+otp,number,apiKey);
						response.sendRedirect("/EnterOtp.html");	
						System.out.println("Hello 5");
					}
					else
					{
						System.out.println("Hello 6");
						out.println("<script src='https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.4/sweetalert2.all.js'></script>");
			            out.println("<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>");
			            out.println("<script>");
			            out.println("$(document).ready(function(){");
			            out.println("swal('ERROR !', 'Your Account Is Under Verification .....Please Try Again Later', 'error');");
			            out.println("});");
			            out.println("</script>");
			            RequestDispatcher rd = request.getRequestDispatcher("/HomePage.html");
			            rd.forward(request, response);
			           
					}
				}
			}
			if(flag==false)
			{
				System.out.println("Hello 7");
				//out.print("invalid emailid or password");
				//response.sendError(1," You Entered Wrong OTP.");
				out.println("<script src='https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.4/sweetalert2.all.js'></script>");
	            out.println("<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>");
	            out.println("<script>");
	            out.println("$(document).ready(function(){");
	            out.println("swal('ERROR !', 'Wrong Email id or Password....Try Again', 'error');");
	            out.println("});");
	            out.println("</script>");
	            RequestDispatcher rd = request.getRequestDispatcher("/HomePage.html");
	            rd.forward(request, response);
	           // response.sendRedirect("HomePage.html");
			}
		}
		catch(Exception p)
		{
			out.print(p);
		}
	
	}

}
