package ppp;
import java.io.BufferedReader;

import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLEncoder;

import javax.net.ssl.HttpsURLConnection;
//import java.util.Random;
public class Otp 
{
	
	public void SendOtp(String message , String number , String apiKey)
	{
		try
		{
			String sendId="FSTSMS";
			String language="english";
			String route="p";
			
			message=URLEncoder.encode(message,"UTF-8");
			
			String myUrl="https://www.fast2sms.com/dev/bulkV2?authorization="+apiKey+"&sender_id="+sendId+"&message="+message+"&language="+language+"&route="+route+"&numbers="+number;
			URL url=new URL(myUrl);
			HttpsURLConnection con=(HttpsURLConnection)url.openConnection();
			
			con.setRequestMethod("GET");
			
			con.setRequestProperty("User-Agent","Mozilla/5.0");
			con.setRequestProperty("cache-control", "no-cache");
			System.out.println("Wait......");
			int responseCode= con.getResponseCode();
			System.out.println("Response Code ;"+responseCode);
			
			StringBuffer response=new StringBuffer();
			
			BufferedReader br=new BufferedReader(new InputStreamReader(con.getInputStream()));
			
			while(true)
			{
				String line=br.readLine();
				
				if(line==null)
				{
					break;
				}
				
				response.append(line);
			}
			System.out.println(response);
			
			}
			catch(Exception e)
			{
				System.out.println(e);
				
			}
	}
	
/*	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Program Started.....");
		
		Otp otp=new Otp();
		String otpmessage=otp.generateOtp(6);
		System.out.println("Generate OTP : "+otpmessage);
		
		String apiKey="s1bapN2kQdCqGvzmRK3xYFi6U4O5MjDyEwur0XcHe7VIAl9SfB2Aj0h7qCm4iIUlvoSVTQ6R1FrYEcyJ";
		String number="8805098268";
		
		SendOtp("Hey , OTP generated by Chocolate Cake "+otpmessage,number,apiKey);
	}*/

}
